[run]
id = "derived_run"
model_spec = "tiny_model"
status = "registered"
created_at = "2026-04-27T19:34:38.011867+00:00"
workspace = "."
tags = []

[packages]
ic = "baseline_ic"
npf = "baseline_npf"
chd = "raised_chd"

[paths]
workspace = "."
run_manifest = "run.toml"
simulation_name_file = "mfsim.nam"
listing_file = "mfsim.lst"
model_name_file = "derived_run.nam"
model_object_file = "derived_run.model"
heads_file = "derived_run.hds"
budget_file = "derived_run.cbc"
