"""Simulation helpers extracted from the MF6 base model module."""

from .base import SimulationBase
from .discretization import DisuGrid, DisvGrid, TemporalDiscretization
from .indexing import (
    build_idomain,
    build_model_times,
    build_ncpl_arr,
    build_node_to_lni,
    build_offsets,
    coerce_per_dates,
)
from .accessors import (
    build_choro,
    build_xsection,
    get_all_heads,
    get_budget,
    get_budget_cumulative,
    get_budget_incremental,
    get_hds,
    get_inputs,
    get_kstpkper,
    get_lak_output,
    get_sfr_output,
    get_surface,
    get_uzf_output,
)
from .packages import (
    CHD,
    GHB,
    LAK,
    UZF,
    Drains,
    InitialConditions,
    KFlow,
    OutputControl,
    Recharge,
    Wells,
    Storage,
)
from .runtime import run_simulation
from .regions import ModelRegion, RegionGroup, RegionRegistry

__all__ = [
    "CHD",
    "DisuGrid",
    "DisvGrid",
    "Drains",
    "GHB",
    "InitialConditions",
    "KFlow",
    "LAK",
    "ModelRegion",
    "RegionGroup",
    "OutputControl",
    "Recharge",
    "Wells",
    "RegionRegistry",
    "SimulationBase",
    "Storage",
    "TemporalDiscretization",
    "UZF",
    "build_idomain",
    "build_model_times",
    "build_ncpl_arr",
    "build_node_to_lni",
    "build_offsets",
    "build_choro",
    "build_xsection",
    "coerce_per_dates",
    "get_all_heads",
    "get_budget",
    "get_budget_cumulative",
    "get_budget_incremental",
    "get_hds",
    "get_inputs",
    "get_kstpkper",
    "get_lak_output",
    "get_sfr_output",
    "get_surface",
    "get_uzf_output",
    "run_simulation",
]
