[run]
id = "source_run"
model_spec = "small_feature_model"
status = "registered"
created_at = "2026-04-27T22:45:01.576453+00:00"
workspace = "."
tags = []

[packages]
ic = "baseline_ic"
npf = "baseline_npf"
chd = "baseline_chd"
rch = "baseline_rch"
uzf = "baseline_uzf"
lak = "baseline_lak"
sfr = "baseline_sfr"

[paths]
workspace = "."
run_manifest = "run.toml"
simulation_name_file = "mfsim.nam"
listing_file = "mfsim.lst"
model_name_file = "source_run.nam"
model_object_file = "source_run.model"
heads_file = "source_run.hds"
budget_file = "source_run.cbc"
