"""Dataclass specifications for the first ``myflopy`` PEST slice."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import pandas as pd

from myflopy.modflow.mf6.observations import (
    DrnFlowTargets,
    HeadTargets,
    LakeStageTargets,
    SfrFlowTargets,
    SfrStageTargets,
)


@dataclass
class VectorParameterSource:
    """Describe a GIS vector source used to define calibration parameters.

    Parameters
    ----------
    path
        Path to a shapefile/geopackage layer.
    value_column
        Base-value column such as ``"k"``, ``"elev"``, or ``"cond"``.
    feature_id_column
        Unique feature identifier column used for feature-based parameters.
    zone_column
        Optional spatial zone column.
    group_column
        Optional logical group column for grouping parameters or observations.
    layer_column
        Optional layer column.
    lower_bound_column, upper_bound_column
        Optional GIS-defined bound columns.
    """

    path: str | Path
    value_column: str
    feature_id_column: str | None = "name"
    zone_column: str | None = None
    group_column: str | None = None
    layer_column: str | None = None
    crs: int | None = 2927
    lower_bound_column: str | None = None
    upper_bound_column: str | None = None


@dataclass
class ExpGeoStruct:
    """Simple exponential geostatistical structure definition.

    This wrapper stores values in a ``myflopy``-friendly form and can be
    converted to a real ``pyemu.geostats.GeoStruct`` lazily when pyEMU is
    available.
    """

    range: float
    contribution: float = 1.0
    anisotropy: float = 1.0
    bearing: float = 0.0
    nugget: float = 0.0
    transform: str = "none"


@dataclass
class HeadTargetObservationSpec:
    """Pre-built head observations for the PEST build, wrapping :class:`HeadTargets`.

    Carries a :class:`~myflopy.modflow.mf6.observations.HeadTargets` plus the
    pyEMU observation-name ``prefix`` and, optionally, an explicit
    ``simulated_values`` table. ``cal.observe(...)`` accepts a bare ``HeadTargets``
    and wraps it for you, so you only construct this spec when you need to pin the
    prefix or supply simulated values directly; the project's native build turns
    it into pyEMU observations + the forward-run head post-processor.

    Parameters
    ----------
    targets
        The head observation locations + target heads to expose.
    simulated_values
        Optional pre-computed simulated-head table; normally regenerated by the
        forward run, so leave ``None``.
    prefix
        pyEMU observation-name prefix (default ``"hds"``).

    See Also
    --------
    myflopy.modflow.mf6.observations.HeadTargets
    """

    targets: HeadTargets
    simulated_values: str | Path | pd.DataFrame | None = None
    prefix: str = "hds"


@dataclass
class LakeStageObservationSpec:
    """Lake-stage observation specification.

    Parameters
    ----------
    lake_names
        Names of lake-stage series to expose as observations.
    values
        Optional target-value table in the same wide/long conventions used by
        :class:`HeadTargets`.
    time_column
        Time/per identifier column when ``values`` is long-form.
    value_column
        Stage-value column when ``values`` is long-form.
    weight
        Optional uniform observation weight to apply when target values are
        supplied.
    prefix
        pyEMU observation-name prefix.
    """

    lake_names: list[str] | None = None
    values: str | Path | pd.DataFrame | None = None
    time_column: str = "time"
    value_column: str = "stage"
    weight: float | None = None
    prefix: str = "stage"
    targets: LakeStageTargets | None = None


@dataclass
class SfrStageObservationSpec:
    """Pre-built SFR-stage observations, wrapping :class:`SfrStageTargets`.

    Pairs a :class:`~myflopy.modflow.mf6.observations.SfrStageTargets` with the
    pyEMU observation-name ``prefix``. ``cal.observe(...)`` accepts a bare
    ``SfrStageTargets`` and wraps it for you; build this spec explicitly only to
    pin a non-default prefix. The native build registers the observations and the
    forward run regenerates the simulated SFR-stage CSV.

    Parameters
    ----------
    targets
        The named-reach stage targets to expose.
    prefix
        pyEMU observation-name prefix (default ``"sfr_stage"``).
    """

    targets: SfrStageTargets
    prefix: str = "sfr_stage"


@dataclass
class SfrFlowObservationSpec:
    """Pre-built SFR-flow observations, wrapping :class:`SfrFlowTargets`.

    Pairs a :class:`~myflopy.modflow.mf6.observations.SfrFlowTargets` with the
    pyEMU observation-name ``prefix``. ``cal.observe(...)`` / ``cal.forecast(...)``
    accept a bare ``SfrFlowTargets`` and wrap it; build this spec explicitly only
    to pin a non-default prefix. Typical for gaged-discharge calibration targets.

    Parameters
    ----------
    targets
        The named-reach flow targets to expose.
    prefix
        pyEMU observation-name prefix (default ``"sfr_flow"``).
    """

    targets: SfrFlowTargets
    prefix: str = "sfr_flow"


@dataclass
class DrnFlowObservationSpec:
    """Pre-built DRN-seepage observations, wrapping :class:`DrnFlowTargets`.

    Pairs a :class:`~myflopy.modflow.mf6.observations.DrnFlowTargets` with the
    pyEMU observation-name ``prefix``. ``cal.observe(...)`` / ``cal.forecast(...)``
    accept a bare ``DrnFlowTargets`` and wrap it; build this spec explicitly only
    to pin a non-default prefix. Used for spring/seep discharge aggregated over
    a group of drain cells.

    Parameters
    ----------
    targets
        The seepage-zone flow targets to expose.
    prefix
        pyEMU observation-name prefix (default ``"drn_flow"``).
    """

    targets: DrnFlowTargets
    prefix: str = "drn_flow"
