"""File-backed model loader built on top of FloPy MF6 loading utilities."""

from __future__ import annotations

from pathlib import Path
from types import MethodType
import hashlib

import flopy
import geopandas as gpd
import numpy as np
import pandas as pd

from myflopy.modflow.mf6.grid.voronoi import VoronoiGridPlus
from myflopy.modflow.mf6.simulation.base import SimulationBase
from myflopy.modflow.mf6.simulation.regions import RegionRegistry
def _progress(verbosity_level: int, message: str):
    """Emit a simple progress message when verbose loading is enabled."""

    if verbosity_level > 0:
        print(f"[LoadedMf6Run] {message}")


def _infer_model_name(workspace: Path) -> str:
    """Infer the groundwater model name file stem for an MF6 workspace."""

    name_files = sorted(path for path in workspace.glob("*.nam") if path.name.lower() != "mfsim.nam")
    if not name_files:
        raise FileNotFoundError(f"No model name file found in workspace: {workspace}")
    return name_files[0].stem


_PACKAGE_SUFFIX_TO_TYPE = {
    "chd": "CHD",
    "dis": "DIS",
    "disu": "DISU",
    "disv": "DISV",
    "drn": "DRN",
    "ghb": "GHB",
    "ic": "IC",
    "lak": "LAK",
    "mvr": "MVR",
    "npf": "NPF",
    "oc": "OC",
    "rch": "RCH",
    "sfr": "SFR",
    "sto": "STO",
    "uzf": "UZF",
}
_PACKAGE_TYPE_TO_SUFFIX = {value: key for key, value in _PACKAGE_SUFFIX_TO_TYPE.items()}
_CORE_PACKAGE_TYPES = {"DIS", "DISU", "DISV", "OC"}


def _discover_package_types(workspace: Path, model_name: str) -> list[str]:
    """Return recognized MF6 package types from files in ``workspace``."""

    package_types: list[str] = []
    for path in sorted(workspace.glob(f"{model_name}.*")):
        suffix = path.suffix.lower().lstrip(".")
        package_type = _PACKAGE_SUFFIX_TO_TYPE.get(suffix)
        if package_type is not None and package_type not in package_types:
            package_types.append(package_type)
    return package_types


def _discover_grid_type(package_types: list[str]) -> str:
    """Infer the grid type from discovered package types."""

    if "DISU" in package_types:
        return "disu"
    if "DISV" in package_types:
        return "disv"
    if "DIS" in package_types:
        return "dis"
    return "unknown"


def _grid_package_path(workspace: Path, model_name: str, grid_type: str) -> Path | None:
    """Return the discretization-package path for a workspace when present."""

    if grid_type not in {"dis", "disu", "disv"}:
        return None
    path = workspace / f"{model_name}.{grid_type}"
    return path if path.exists() else None


def _file_sha256(path: Path) -> str:
    """Return a normalized SHA-256 hash of one text MF6 package file.

    Leading comment lines generated by FloPy contain timestamps and should not
    cause otherwise identical discretization files to compare as different.
    """

    digest = hashlib.sha256()
    with path.open("r", encoding="utf-8", errors="ignore") as handle:
        for line in handle:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            digest.update(stripped.encode("utf-8"))
            digest.update(b"\n")
    return digest.hexdigest()


def _coerce_top_array(top, ncpl: int) -> np.ndarray:
    """Normalize top elevation data to a one-dimensional ``ncpl``-length array."""

    values = np.asarray(top, dtype=float).reshape(-1)
    if values.size == 1:
        values = np.repeat(values, ncpl)
    if values.size != ncpl:
        raise ValueError(f"Top array size {values.size} does not match ncpl {ncpl}.")
    return values


def _coerce_botm_layers(botm, ncpl: int) -> np.ndarray:
    """Normalize bottom elevation data to a ``(nlay, ncpl)`` array."""

    values = np.asarray(botm, dtype=float)
    if values.ndim == 0:
        return np.repeat(values.reshape(1), ncpl).reshape(1, ncpl)
    if values.ndim == 1:
        if values.size == ncpl:
            return values.reshape(1, ncpl)
        if values.size % ncpl == 0:
            return values.reshape(values.size // ncpl, ncpl)
    if values.ndim >= 2:
        trailing = int(np.prod(values.shape[1:]))
        if trailing == ncpl:
            return values.reshape(values.shape[0], ncpl)
    raise ValueError(f"Bottom array shape {values.shape} cannot be reshaped to ncpl {ncpl}.")


def _build_voronoi_from_modelgrid(
    modelgrid,
    *,
    crs: str,
    name: str,
) -> VoronoiGridPlus:
    """Reconstruct a ``VoronoiGridPlus`` view from an MF6 vertex grid."""

    verts = np.asarray(modelgrid.verts, dtype=float)
    iverts = [[int(vertex) for vertex in cell] for cell in modelgrid.iverts]
    xcyc = np.column_stack(
        [
            np.asarray(modelgrid.xcellcenters, dtype=float).reshape(-1),
            np.asarray(modelgrid.ycellcenters, dtype=float).reshape(-1),
        ]
    )
    return VoronoiGridPlus(
        verts=verts,
        iverts=iverts,
        xcyc=xcyc,
        crs=crs,
        name=name,
    )


def _build_topbtm_frame(vor: VoronoiGridPlus, gwf) -> gpd.GeoDataFrame:
    """Build the top/bottom GeoDataFrame expected by ``VoronoiGridPlus`` helpers."""

    ncpl = vor.ncpl
    top = _coerce_top_array(gwf.modelgrid.top, ncpl)
    botm_layers = _coerce_botm_layers(gwf.modelgrid.botm, ncpl)

    data: dict[object, object] = {
        "geometry": vor.gdf_vorPolys.geometry,
        0: top,
    }
    for idx, layer_botm in enumerate(botm_layers, start=1):
        data[idx] = layer_botm
    return gpd.GeoDataFrame(data, geometry="geometry", crs=vor.crs)


def _grid_ncpl(modelgrid) -> int:
    """Return the number of cells per layer from an MF6 model grid."""

    return int(np.asarray(modelgrid.xcellcenters, dtype=float).reshape(-1).size)


def _extract_idomain(gwf) -> list[int] | None:
    """Extract a flattened idomain list from DISV or DISU packages when present."""

    for package_name in ("disu", "disv"):
        package = getattr(gwf, package_name, None)
        if package is None or getattr(package, "idomain", None) is None:
            continue
        values = np.asarray(package.idomain.array).reshape(-1)
        if values.size and all(value is not None for value in values):
            return values.astype(int).tolist()
    return None


def load_mf6_run(
    workspace: Path,
    *,
    model_name: str | None = None,
    crs: str = "EPSG:2927",
    verbosity_level: int = 0,
):
    """Open any MF6 workspace as a lazy, file-backed model for inspection.

    Unlike :func:`load_run` (which reopens a myflopy-managed :class:`Run` from its
    manifest), this loads a *plain* MF6 workspace -- any folder with ``mfsim.nam``,
    however it was created -- into a :class:`LoadedMf6Run` that lazily exposes the
    grid, heads, budgets and packages. Handy for post-processing external models or
    inside a PEST forward run.

    Parameters
    ----------
    workspace
        Directory containing the MF6 simulation files.
    model_name
        Which model to load (defaults to the first GWF model).
    crs
        CRS to attach to the grid (default ``"EPSG:2927"``).
    verbosity_level
        ``0`` silent, higher prints progress.

    Examples
    --------
    >>> model = mf.load_mf6_run("path/to/mf6_run")
    >>> model.load_all()
    >>> heads = model.hds.array()
    """

    _progress(verbosity_level, f"Opening workspace: {workspace}")
    return LoadedMf6Run(
        workspace=workspace,
        model_name=model_name,
        crs=crs,
        verbosity_level=verbosity_level,
    )


def _simulation_plot_compat(sim, model_list=None, SelPackList=None, **kwargs):
    """Compatibility shim for FloPy simulation plotting."""

    from flopy.plot.plotutil import PlotUtilities

    return PlotUtilities._plot_simulation_helper(
        sim,
        model_list=model_list,
        SelPackList=SelPackList,
        **kwargs,
    )


def patch_simulation_plot(sim):
    """Replace a loaded simulation's ``.plot`` with a compatibility shim, in place.

    FloPy's ``MFSimulation.plot`` can raise on simulations reloaded from disk
    (e.g. unstructured grids or partially populated output). This binds a
    forgiving ``_simulation_plot_compat`` method onto ``sim`` so ``sim.plot(...)``
    works after a reload. Applied automatically by the run loaders; call it
    yourself only on a hand-loaded simulation.

    Parameters
    ----------
    sim
        The FloPy ``MFSimulation`` to patch (mutated in place).

    Returns
    -------
    The same ``sim``, for chaining.
    """
    sim.plot = MethodType(_simulation_plot_compat, sim)
    return sim


class LoadedMf6Run(SimulationBase):
    """File-backed exploration object built from MF6 input and output files.

    Parameters
    ----------
    workspace
        Path to a standard MF6 run directory.
    crs
        CRS assigned to the reconstructed ``VoronoiGridPlus`` view if one is
        built lazily later.
    verbosity_level
        FloPy-style verbosity plus simple progress messages from this loader.
    """

    def __init__(
        self,
        *,
        workspace: Path,
        model_name: str | None = None,
        crs: str = "EPSG:2927",
        verbosity_level: int = 0,
    ):
        workspace = Path(workspace)
        if not workspace.exists():
            raise FileNotFoundError(f"Run workspace does not exist: {workspace}")

        model_name = _infer_model_name(workspace) if model_name is None else model_name
        available_package_types = _discover_package_types(workspace, model_name)
        grid_type = _discover_grid_type(available_package_types)

        self.name = model_name
        self._sim = None
        self._gwf = None
        self.ims = None
        self._crs = crs
        self._verbosity_level = verbosity_level
        self._vor = None
        self.nper = None
        self.nlay = None
        self.num_steps = None
        self.per_len = None
        self._obs = None
        self._times = None
        self.model_output_folder_path = workspace
        self._master_celld = {}
        self._hds = None
        self._idomain_path = None
        self._bud = None
        self._per_dates = None
        self._idomain_gdf = None
        self._inactive_cells = None
        self._node_to_lni = None
        self._lni_to_node = None
        self._kstpkper = None
        self._idomain = None
        self._grid_type_override = grid_type if grid_type != "unknown" else None
        self._targets = None
        self._visualize = None
        self._particle_tracking = None
        self._parallel = None
        self.regions = RegionRegistry(self)
        self.source = "mf6_files"
        self._model_name = model_name
        self._available_package_types = tuple(available_package_types)
        self._available_package_types_lower = {value.lower() for value in available_package_types}
        self._loaded_package_types: set[str] = set()
        self._fully_loaded = False
        self._core_loaded = False
        self._shared_vor_source = None
        _progress(
            verbosity_level,
            (
                f"Prepared lazy file-backed model '{self.name}' "
                f"(grid_type={self.grid_type}, packages={list(self.package_names)}). "
                "Grid, outputs, and package definitions will load only when needed."
            ),
        )

    @property
    def sim(self):
        """Lazily loaded FloPy simulation object."""

        self._ensure_core_loaded()
        return self._sim

    @sim.setter
    def sim(self, value):
        self._sim = value

    @property
    def gwf(self):
        """Lazily loaded FloPy groundwater-flow model object."""

        self._ensure_core_loaded()
        return self._gwf

    @gwf.setter
    def gwf(self, value):
        self._gwf = value

    @property
    def package_names(self) -> list[str]:
        """Recognized package names for the run workspace.

        This is discovered from package filenames and therefore stays cheap even
        before any FloPy packages are loaded.
        """

        return list(self._available_package_types)

    def _summary_ncpl(self) -> int | None:
        """Return cached ``ncpl`` for a lightweight summary when possible."""

        if self._vor is not None:
            return int(self._vor.ncpl)
        if self._gwf is not None:
            return _grid_ncpl(self._gwf.modelgrid)
        return None

    def _summary_nlay(self) -> int | None:
        """Return cached layer count for :meth:`summary`."""

        return self.nlay

    def _summary_nper(self) -> int | None:
        """Return cached stress-period count for :meth:`summary`."""

        return self.nper

    def package_summary(self) -> pd.DataFrame:
        """Return a lightweight package table discovered from package filenames."""

        rows = []
        for package_type in self.package_names:
            suffix = _PACKAGE_TYPE_TO_SUFFIX.get(package_type, package_type.lower())
            path = self.workspace / f"{self.name}.{suffix}"
            rows.append(
                {
                    "package": package_type,
                    "package_type": package_type.lower(),
                    "filename": path.name if path.exists() else None,
                }
            )
        return pd.DataFrame(rows)

    @property
    def modelgrid(self):
        """Underlying FloPy modelgrid object, loaded only when needed."""

        self._ensure_core_loaded()
        return self._gwf.modelgrid

    def _normalize_package_names(self, package_names: str | list[str] | tuple[str, ...] | set[str]) -> list[str]:
        """Normalize package names into lower-case MF6 package identifiers."""

        if isinstance(package_names, (list, tuple, set)):
            return [str(name).lower() for name in package_names]
        return [str(package_names).lower()]

    def _load_simulation(
        self,
        *,
        load_only: list[str] | None,
        mark_full: bool,
        reason: str,
    ):
        """Load the FloPy simulation with the requested package subset."""

        display_verbosity = self._verbosity_level if self._verbosity_level > 0 else 1

        if load_only is None:
            _progress(display_verbosity, f"Loading full MF6 simulation from: {self.workspace}")
        else:
            _progress(
                display_verbosity,
                f"Loading MF6 packages for {reason}: {', '.join(package.upper() for package in load_only)}",
            )
        sim = flopy.mf6.MFSimulation.load(
            sim_ws=str(self.workspace),
            load_only=load_only,
            lazy_io=True,
            verbosity_level=display_verbosity,
        )
        patch_simulation_plot(sim)
        _progress(display_verbosity, f"Locating GWF model '{self._model_name}'")
        gwf = sim.get_model(self._model_name)
        if gwf is None:
            raise FileNotFoundError(
                f"Could not load GWF model '{self._model_name}' from workspace: {self.workspace}"
            )

        self._sim = sim
        self._gwf = gwf
        self.nper = int(sim.tdis.nper.data)
        self.nlay = int(np.asarray(gwf.modelgrid.botm).reshape(-1).size / _grid_ncpl(gwf.modelgrid))
        if self._idomain is None:
            self._idomain = _extract_idomain(gwf)
        self._loaded_package_types = {name.upper() for name in gwf.get_package_list()}
        self._core_loaded = True
        self._fully_loaded = mark_full or self._loaded_package_types >= set(self.package_names)

    def _ensure_core_loaded(self):
        """Ensure core grid/output infrastructure is available."""

        if self._core_loaded and self._gwf is not None:
            return
        available = [name.lower() for name in self.package_names if name in _CORE_PACKAGE_TYPES]
        if self.grid_type in {"dis", "disu", "disv"} and self.grid_type not in available:
            available.insert(0, self.grid_type)
        if "oc" not in available and "OC" in self.package_names:
            available.append("oc")
        self._load_simulation(load_only=available or None, mark_full=False, reason="core access")

    def _ensure_packages_loaded(self, package_names: list[str]):
        """Ensure one or more named packages are available on ``self.gwf``."""

        normalized = self._normalize_package_names(package_names)
        if all(name.upper() in self._loaded_package_types for name in normalized):
            return

        # For exploratory file-backed workflows, repeatedly reloading FloPy with a
        # slightly larger ``load_only`` set is much slower than paying one full
        # load once. After the initial core/grid load, the first non-core package
        # request therefore upgrades the loaded run to a full package load.
        missing_non_core = [
            name for name in normalized
            if name.upper() not in _CORE_PACKAGE_TYPES and name.upper() not in self._loaded_package_types
        ]
        if missing_non_core and not self._fully_loaded:
            self._load_simulation(load_only=None, mark_full=True, reason="package access warm load")
            return

        target = {name.lower() for name in normalized}
        target.update(name.lower() for name in self._loaded_package_types)
        target.update(name.lower() for name in self.package_names if name in _CORE_PACKAGE_TYPES)
        if self.grid_type in {"dis", "disu", "disv"}:
            target.add(self.grid_type)
        self._load_simulation(
            load_only=sorted(target),
            mark_full=False,
            reason="package access",
        )

    @property
    def vor(self) -> VoronoiGridPlus:
        """Build and cache a ``VoronoiGridPlus`` view on first access."""

        if self._shared_vor_source is not None:
            return self._shared_vor_source.vor
        if self._vor is None:
            self._ensure_core_loaded()
            _progress(self._verbosity_level, "Building Voronoi grid view from the MF6 modelgrid")
            vor = _build_voronoi_from_modelgrid(self._gwf.modelgrid, crs=self._crs, name=self.name)
            vor.gdf_topbtm = _build_topbtm_frame(vor, self._gwf)
            self._vor = vor
            _progress(self._verbosity_level, f"Voronoi grid ready (ncpl={self._vor.ncpl})")
        return self._vor

    def grid_signature(self) -> str | None:
        """Return a stable signature for the run's discretization package.

        For file-backed runs this uses the exact ``.dis/.disv/.disu`` file
        bytes, which allows higher-level helpers such as ``ModelGroup`` to
        confirm grids match without forcing full grid reconstruction first.
        """

        grid_path = _grid_package_path(self.workspace, self.name, self.grid_type)
        if grid_path is None:
            return None
        return _file_sha256(grid_path)

    def package(self, package_names: str | list[str]):
        """Load and return one or more MF6 package objects on demand."""

        normalized = self._normalize_package_names(package_names)
        if len(normalized) > 1:
            self._ensure_packages_loaded(normalized)
            return {name: self.package(name) for name in normalized}

        package_name = normalized[0]
        self._ensure_packages_loaded([package_name])
        package = self._gwf.get_package(package_name)
        if package is None and self._sim is not None:
            package = self._sim.get_package(package_name)
        if package is None:
            raise AttributeError(f"Package {package_name!r} is not available in run '{self.name}'.")
        return package

    def _get_budget_reader(self):
        """Return the binary cell-budget reader without loading FloPy core packages."""

        if self._bud is None:
            # MF6 always writes double-precision binaries. FloPy's default
            # precision="auto" tries single first and can misread a double file:
            # on Windows the bogus record length makes file.seek raise
            # OSError (Errno 22) -- which escapes FloPy's BudgetIndexError/EOFError
            # guard, so the double-precision fallback never runs. Read as double.
            self._bud = flopy.utils.CellBudgetFile(
                self.workspace / f"{self.name}.cbc", precision="double"
            )
        return self._bud

    def _get_budget_kstpkper(self) -> list[tuple[int, int]]:
        """Return budget ``(kstp, kper)`` pairs directly from the ``.cbc`` file."""

        if self._kstpkper is None:
            self._kstpkper = [
                tuple(int(value) for value in pair)
                for pair in self._get_budget_reader().get_kstpkper()
            ]
        return self._kstpkper

    def load_all(self):
        """Fully load the MF6 simulation and all discovered packages."""

        if not self._fully_loaded:
            self._load_simulation(load_only=None, mark_full=True, reason="full load")
        return self

    def run_simulation(self):
        """Rewrite the loaded simulation files and run MF6 from the workspace."""

        self.load_all()
        self._sim.write_simulation()
        success, buff = self._sim.run_simulation(silent=False, report=True)
        return success, buff
