"""Grid helpers extracted from the MF6 Voronoi modules."""

from .connectivity import build_disu_connectivity
from .helpers import (
    densify_poly,
    flatten,
    get_griddata_from_disu,
    rows_truncate_at_first_missing,
    signed_area,
)
from .selection import (
    get_grid_edge_cells,
    get_model_boundary_polygons,
    get_vor_cells_as_dict,
    get_vor_cells_as_series,
)
from .plotting import (
    GridSection,
    build_choropleth,
    build_grid_section,
    get_dash_selector,
    map_nodes,
    mapit,
    plot2d,
    plot3d,
    plottri,
    show,
    show_overlapping_geometry,
    show_selected_cells,
)
from .geometry import (
    adjust_cells_by_id,
    adjust_top_btm_overlaps,
    calculate_distance,
    find_adjacent_cells,
    find_adjacent_polygons,
    generate_grid_around_point,
    generate_grid_coordinates,
    generate_grid_polygons,
    get_centroids,
    get_gdf_latlon,
    get_gdf_vor_polys,
    get_grid_centroid,
    get_latlon,
    get_overlapping_area,
    get_vor_idx_from_geometry,
    get_vor_idx_from_geometry_idx,
    get_voronoi_polygons,
    reconcile_surfaces,
    set_k_vor,
    shared_face_length,
    voronoi_refine_by_point,
)
from .surfaces import (
    get_cell_areas,
    get_domain,
    get_gdf_topbtm_multilyr,
    get_normal_from_strike_and_dip,
    get_origin_xy,
    get_raster_from_strike_dip,
    get_raster_vals_at_centroids,
)
from .triangle import MeshBuildProfile, TriangleGrid
from .voronoi import VoronoiGridPlus

__all__ = [
    "build_disu_connectivity",
    "densify_poly",
    "flatten",
    "GridSection",
    "adjust_cells_by_id",
    "adjust_top_btm_overlaps",
    "build_choropleth",
    "build_grid_section",
    "calculate_distance",
    "get_griddata_from_disu",
    "get_dash_selector",
    "get_grid_edge_cells",
    "find_adjacent_cells",
    "find_adjacent_polygons",
    "generate_grid_around_point",
    "generate_grid_coordinates",
    "generate_grid_polygons",
    "get_centroids",
    "get_gdf_latlon",
    "get_gdf_vor_polys",
    "get_model_boundary_polygons",
    "get_grid_centroid",
    "get_latlon",
    "map_nodes",
    "mapit",
    "plot2d",
    "plot3d",
    "plottri",
    "show",
    "show_overlapping_geometry",
    "show_selected_cells",
    "get_cell_areas",
    "get_domain",
    "get_gdf_topbtm_multilyr",
    "get_normal_from_strike_and_dip",
    "get_origin_xy",
    "get_raster_from_strike_dip",
    "get_raster_vals_at_centroids",
    "get_overlapping_area",
    "get_vor_idx_from_geometry",
    "get_vor_idx_from_geometry_idx",
    "get_voronoi_polygons",
    "reconcile_surfaces",
    "get_vor_cells_as_dict",
    "get_vor_cells_as_series",
    "rows_truncate_at_first_missing",
    "set_k_vor",
    "shared_face_length",
    "signed_area",
    "TriangleGrid",
    "MeshBuildProfile",
    "VoronoiGridPlus",
    "voronoi_refine_by_point",
]
