"""Compatibility exports for the legacy MF6 base module."""

from __future__ import annotations

from myflopy.modflow.mf6.simulation import (
    CHD,
    GHB,
    ModelRegion,
    RegionGroup,
    UZF,
    DisuGrid,
    DisvGrid,
    Drains,
    InitialConditions,
    KFlow,
    OutputControl,
    Recharge,
    RegionRegistry,
    SimulationBase,
    Storage,
    TemporalDiscretization,
    build_choro,
    build_idomain,
    build_model_times,
    build_ncpl_arr,
    build_node_to_lni,
    build_offsets,
    build_xsection,
    coerce_per_dates,
    get_all_heads,
    get_budget,
    get_budget_cumulative,
    get_budget_incremental,
    get_hds,
    get_inputs,
    get_kstpkper,
    get_lak_output,
    get_sfr_output,
    get_surface,
    get_uzf_output,
    run_simulation,
)
from myflopy.modflow.mf6.chd import CHDFromVector
from myflopy.modflow.mf6.drn import DRNFromVector
from myflopy.modflow.mf6.ghb import GHBFromVector
from myflopy.modflow.mf6.kflow import KFromVector
from myflopy.modflow.mf6.recharge import RCHFromVector

__all__ = [
    "CHD",
    "CHDFromVector",
    "DRNFromVector",
    "DisuGrid",
    "DisvGrid",
    "Drains",
    "GHB",
    "GHBFromVector",
    "InitialConditions",
    "KFromVector",
    "KFlow",
    "ModelRegion",
    "RegionGroup",
    "OutputControl",
    "Recharge",
    "RCHFromVector",
    "RegionRegistry",
    "SimulationBase",
    "Storage",
    "TemporalDiscretization",
    "UZF",
    "build_choro",
    "build_idomain",
    "build_model_times",
    "build_ncpl_arr",
    "build_node_to_lni",
    "build_offsets",
    "build_xsection",
    "coerce_per_dates",
    "get_all_heads",
    "get_budget",
    "get_budget_cumulative",
    "get_budget_incremental",
    "get_hds",
    "get_inputs",
    "get_kstpkper",
    "get_lak_output",
    "get_sfr_output",
    "get_surface",
    "get_uzf_output",
    "run_simulation",
]
