[run]
id = "cum9a_algo7h"
model_spec = "legacy_archive"
status = "imported"
created_at = "2026-04-25T19:26:27.220090+00:00"
workspace = "C:/Users/lukem/mf6/cum9a_algo7h"
tags = ["cum"]

[paths]
workspace = "C:/Users/lukem/mf6/cum9a_algo7h"
run_manifest = "run.toml"
simulation_name_file = "mfsim.nam"
listing_file = "mfsim.lst"
model_name_file = "cum9a_algo7h.nam"
model_object_file = "cum9a_algo7h.model"
heads_file = "cum9a_algo7h.hds"
budget_file = "cum9a_algo7h.cbc"
disv_file = "cum9a_algo7h.disv"

[metadata]
source_root = "C:\\Users\\lukem\\mf6"
relative_workspace = "cum9a_algo7h"
family = "cum"
has_mfsim = true
has_heads = true
has_budget = true
grid_type = "disv"
