[run]
id = "cum_varpit_felf"
model_spec = "legacy_archive"
status = "imported"
created_at = "2026-04-25T19:26:27.224456+00:00"
workspace = "C:/Users/lukem/mf6/cum_varpit_felf"
tags = ["cum"]

[paths]
workspace = "C:/Users/lukem/mf6/cum_varpit_felf"
run_manifest = "run.toml"
simulation_name_file = "mfsim.nam"
listing_file = "mfsim.lst"
model_name_file = "cum_varpit_felf.nam"
model_object_file = "cum_varpit_felf.model"
heads_file = "cum_varpit_felf.hds"
budget_file = "cum_varpit_felf.cbc"
disv_file = "cum_varpit_felf.disv"

[metadata]
source_root = "C:\\Users\\lukem\\mf6"
relative_workspace = "cum_varpit_felf"
family = "cum"
has_mfsim = true
has_heads = true
has_budget = true
grid_type = "disv"
