[run]
id = "Lkpt_F9b"
model_spec = "legacy_archive"
status = "imported"
created_at = "2026-04-25T19:26:27.286185+00:00"
workspace = "C:/Users/lukem/mf6/Lkpt_F9b"
tags = ["lkpt"]

[paths]
workspace = "C:/Users/lukem/mf6/Lkpt_F9b"
run_manifest = "run.toml"
simulation_name_file = "mfsim.nam"
listing_file = "mfsim.lst"
model_name_file = "Lkpt_F9b.nam"
model_object_file = "Lkpt_F9b.model"
heads_file = "Lkpt_F9b.hds"
budget_file = "Lkpt_F9b.cbc"
disv_file = "Lkpt_F9b.disv"

[metadata]
source_root = "C:\\Users\\lukem\\mf6"
relative_workspace = "Lkpt_F9b"
family = "lkpt"
has_mfsim = true
has_heads = true
has_budget = true
grid_type = "disv"
