[run]
id = "ssb_new_phs1alt"
model_spec = "legacy_archive"
status = "imported"
created_at = "2026-04-25T19:26:27.307847+00:00"
workspace = "C:/Users/lukem/mf6/ssb_new_phs1alt"
tags = ["ssb"]

[paths]
workspace = "C:/Users/lukem/mf6/ssb_new_phs1alt"
run_manifest = "run.toml"
simulation_name_file = "mfsim.nam"
listing_file = "mfsim.lst"
model_name_file = "ssb_new_phs1alt.nam"
model_object_file = "ssb_new_phs1alt.model"
heads_file = "ssb_new_phs1alt.hds"
budget_file = "ssb_new_phs1alt.cbc"
disv_file = "ssb_new_phs1alt.disv"

[metadata]
source_root = "C:\\Users\\lukem\\mf6"
relative_workspace = "ssb_new_phs1alt"
family = "ssb"
has_mfsim = true
has_heads = true
has_budget = true
grid_type = "disv"
