[run]
id = "tw2_aqtest"
model_spec = "legacy_archive"
status = "imported"
created_at = "2026-04-25T19:26:27.307847+00:00"
workspace = "C:/Users/lukem/mf6/tw2_aqtest"
tags = ["tw"]

[paths]
workspace = "C:/Users/lukem/mf6/tw2_aqtest"
run_manifest = "run.toml"
simulation_name_file = "mfsim.nam"
listing_file = "mfsim.lst"
model_name_file = "tw2_aqtest.nam"
model_object_file = "tw2_aqtest.model"
heads_file = "tw2_aqtest.hds"
budget_file = "tw2_aqtest.cbc"
disv_file = "tw2_aqtest.disv"

[metadata]
source_root = "C:\\Users\\lukem\\mf6"
relative_workspace = "tw2_aqtest"
family = "tw"
has_mfsim = true
has_heads = true
has_budget = true
grid_type = "disv"
